steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      [
        '--dockerfile=Dockerfile',
        '--context=.',
        '--cache=true',
        '--cache-ttl=6h',
        '--destination=gcr.io/wikiconnect-2803b/wiki-service',
      ]
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'wiki-service',
        '--image',
        'gcr.io/wikiconnect-2803b/wiki-service',
        '--platform',
        'managed',
        '--region',
        'us-central1',
        '--allow-unauthenticated'
      ]